apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/instance: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/part-of: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
        backstage.io/kubernetes-id: ${{ values.component_id }}
    spec:
      containers:
      - image: ${{ values.image_url }}:${{ values.image_tag }}
        name: ${{ values.component_id }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: PORT
          value: "8080"
