apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/instance: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: ${{ values.component_id }}
  type: ClusterIP
