apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: ${{ values.argocd_namespace }}
  labels:
    backstage.io/kubernetes-id: ${{ values.component_id }}
    app: ${{ values.component_id }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://${{ values.destination.host }}/${{ values.destination.owner }}/${{ values.destination.repo }}
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: ${{ values.enable_auto_heal }}
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
